-- 1. Create guests table
create table guests (
  id                bigint primary key generated always as identity,
  first_name        text not null,
  last_name         text,
  address           text,
  email             text,
  invited_by        text,
  age               text,
  relationship      text,
  save_the_date     text,
  invitation        text,
  response          text,
  attending         int,
  children          int,
  rehearsal_invited int,
  rehearsal_going   text,
  dietary           text,
  table_num         int,
  gift_desc         text,
  thankyou_sent     text,
  notes             text,
  created_at        timestamptz default now()
);

-- 2. Seed all 79 guests from the spreadsheet
insert into guests (first_name, last_name, invited_by, age, relationship, save_the_date, invitation, response, attending, rehearsal_invited, dietary, table_num, notes) values
('Cheryl','Beasley','Jordan','ADULT','IMMEDIATE FAM','Sent','Sent','Maybe',2,1,'Vegetarian',1,'Additional notes');

insert into guests (first_name, last_name, invited_by, age, relationship) values
('Jeff','Beasley','Jordan','ADULT','IMMEDIATE FAM'),
('Marc','Redman','Paul','ADULT','IMMEDIATE FAM'),
('Anabelle','Redman','Paul','ADULT','IMMEDIATE FAM'),
('Missy','Scherber','Paul','ADULT','IMMEDIATE FAM'),
('Trevor','Scherber','Paul','ADULT','IMMEDIATE FAM'),
('Brooklyn','Lyles','Paul','TEEN','IMMEDIATE FAM'),
('Bayler','Lyles','Paul','TEEN','IMMEDIATE FAM'),
('Laura','Larson','Paul','ADULT','IMMEDIATE FAM'),
('Chris','Larson','Paul','ADULT','IMMEDIATE FAM'),
('Kristen','Lawson','Jordan','ADULT','WEDDING PARTY'),
('Jon','Husband','Jordan','ADULT','FRIEND'),
('Ashley','Hicks','Jordan','ADULT','WEDDING PARTY'),
('Kyle','Hicks','Jordan','ADULT','FAMILY DAD'),
('Johanna','Strong','Jordan','ADULT','WEDDING PARTY'),
('Travis',null,'Jordan','ADULT','FRIEND'),
('Taylor','Quillian','Jordan','ADULT','WEDDING PARTY'),
('Adam','Quillian','Jordan','ADULT','FRIEND'),
('Milos','Ristanovic','Paul','ADULT','WEDDING PARTY'),
('Tea','Ristanovic','Paul','ADULT','FRIEND'),
('Jay','Higgins','Paul','ADULT','WEDDING PARTY'),
('Kelly','Higgins','Paul','ADULT','FRIEND'),
('Tor','Anderson','Paul','ADULT','WEDDING PARTY'),
('Kinsie','Anderson','Paul','ADULT','FRIEND'),
('Erik','Haugan','Paul','ADULT','WEDDING PARTY'),
('Billy','Guerrero','Paul','ADULT','FAMILY MOM'),
('Judie','Redman','Paul','ADULT','FAMILY DAD'),
('Ben','Redman','Paul','ADULT','FAMILY DAD'),
('Karen','Redman','Paul','ADULT','FAMILY DAD'),
('Liam','Redman','Paul','TEEN','FAMILY DAD'),
('Jeremy','Redman','Paul','ADULT','FAMILY DAD'),
('Tiffany','Redman','Paul','ADULT','FAMILY DAD'),
('Leslie','Haffley','Paul','ADULT','FAMILY DAD'),
('Jordan','Haffley','Paul','ADULT','FAMILY DAD'),
('Chloe','Haffley','Paul','ADULT','FAMILY DAD'),
('Jesse','Haffley','Paul','ADULT','FAMILY DAD'),
('Emily','Haffley','Paul','ADULT','FAMILY DAD'),
('John','Haffley','Paul','ADULT','FAMILY DAD'),
('Amber','Haffley','Paul','ADULT','FAMILY DAD'),
('Phillip','Hutto','Jordan','ADULT','FAMILY MOM'),
('Leanne',null,'Jordan','ADULT','FAMILY MOM'),
('Allison','Moore','Jordan','ADULT','FAMILY MOM'),
('Jason','Moore','Jordan','ADULT','FAMILY MOM'),
('Bill','Beasley','Jordan','ADULT','FAMILY DAD'),
('Nell','Beasley','Jordan','ADULT','FAMILY DAD'),
('Marion','Williams','Jordan','ADULT','FAMILY DAD'),
('Debbie','Clarke','Jordan','ADULT','FAMILY DAD'),
('Billy','Beasley','Jordan','ADULT','FAMILY DAD'),
('Margaret','Beasley','Jordan','ADULT','FAMILY DAD'),
('Jimmy','Beasley','Jordan','ADULT','FAMILY DAD'),
('Brian','Beasley','Jordan','ADULT','FAMILY DAD'),
('Brenda','Beasley','Jordan','ADULT','FAMILY DAD'),
('Jamie','Balliet','Jordan','ADULT','FAMILY DAD'),
('Karen','Balliet','Jordan','ADULT','FAMILY DAD'),
('Michelle','Brady','Jordan','ADULT','FAMILY DAD'),
('Cheryl','Lawson','Jordan','ADULT','FRIEND'),
('Ken','Lawson','Jordan','ADULT','FRIEND'),
('Amanda','Ingwerson','Jordan','ADULT','FRIEND'),
('Nick','Ingwerson','Jordan','ADULT','FRIEND'),
('Brooke','Liberatore','Jordan','ADULT','FRIEND'),
('Justin','Liberatore','Jordan','ADULT','FRIEND'),
('Ben','Salaba','Paul','ADULT','FRIEND'),
('Rachel','Salaba','Paul','ADULT','FRIEND'),
('Trevor','Bisping','Paul','ADULT','FRIEND'),
('Carly','Bisping','Paul','ADULT','FRIEND'),
('Jack','Storry','Paul','ADULT','FRIEND'),
('Lauren','Storry','Paul','ADULT','FRIEND'),
('Eddie','Turner','Paul','ADULT','FRIEND'),
('Alyssa','Turner','Paul','ADULT','FRIEND'),
('Devin','Kuhns','Paul','ADULT','FRIEND'),
('Isabelle','Scherber','Paul','CHILD','IMMEDIATE FAM'),
('Tucker','Scherber','Paul','CHILD','IMMEDIATE FAM'),
('Aubrey','Scherber','Paul','CHILD','IMMEDIATE FAM'),
('Griffin','Larson','Paul','CHILD','IMMEDIATE FAM'),
('Theo','Larson','Paul','CHILD','IMMEDIATE FAM'),
('Watson','Larson','Paul','CHILD','IMMEDIATE FAM'),
('Alexandria','Larson','Paul','CHILD','IMMEDIATE FAM'),
('Alaina','Moore','Jordan','CHILD','FAMILY MOM'),
('Rylee',null,'Jordan','CHILD','FRIEND');
